backend:
  name: github
  repo: thefoxboxman/hugo-restaurant-tutorial.git
  branch: master

media_folder: "scr/img/gallery"  #folder where uploaded image files should go

collections:
  - name: food
    label: "Food Item"
    folder: "site/content/food"
    create: true
    fields:
    - {label: "Name of Item", name: "title", widget: "string"}
    - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
    - {label: "Ingredients/Description", name: "description", widget: "stext"}
    - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
    - {label: "Price", name: "price", widget: "string"}