backend:
  name: github
  repo: thefoxboxman/hugo-restaurant-tutorial
  branch: master

media_folder: "scr/img/gallery"  #folder where uploaded image files should go

publish_mode: editorial_workflow

collections:
  - name: food
    label: "Food Item"
    folder: "site/content/food"
    create: true
    fields:
    - {label: "Name of Item", name: "title", widget: "string"}
    - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
    - {label: "Ingredients/Description", name: "description", widget: "text"}
    - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
    - {label: "Price", name: "price", widget: "string"}

  - name: drinks
      label: "Drinks Item"
      folder: "site/content/drinks"
      create: true
      fields:
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Drink Types", name: "categories", widget: "list", default: ["beer", "cocktails", "wine", "soft drinks"]}
      - {label: "Type", name: "type", widget: "string", default: "default"}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}